# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Validation_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Validation(object):
    def setupUi(self, Validation):
        Validation.setObjectName("Validation")
        Validation.setWindowModality(QtCore.Qt.NonModal)
        Validation.resize(480, 149)
        Validation.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Validation.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Users/yuanming3/Pictures/th.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Validation.setWindowIcon(icon)
        Validation.setAutoFillBackground(False)
        Validation.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(Validation)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 6, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(60, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_accept = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_accept.setGeometry(QtCore.QRect(280, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_accept.setFont(font)
        self.pushButton_accept.setObjectName("pushButton_accept")
        Validation.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Validation)
        self.statusbar.setObjectName("statusbar")
        Validation.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(Validation)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        Validation.setMenuBar(self.menuBar)
        self.actionMannual = QtWidgets.QAction(Validation)
        self.actionMannual.setObjectName("actionMannual")
        self.actionAbout = QtWidgets.QAction(Validation)
        self.actionAbout.setObjectName("actionAbout")
        self.actionReadme = QtWidgets.QAction(Validation)
        self.actionReadme.setObjectName("actionReadme")
        self.actionImport = QtWidgets.QAction(Validation)
        self.actionImport.setObjectName("actionImport")
        self.menuHelp.addAction(self.actionImport)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionReadme)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Validation)
        QtCore.QMetaObject.connectSlotsByName(Validation)

    def retranslateUi(self, Validation):
        _translate = QtCore.QCoreApplication.translate
        Validation.setWindowTitle(_translate("Validation", "Validation"))
        self.label.setText(_translate("Validation", "Order Number:"))
        self.pushButton_login.setText(_translate("Validation", "登录"))
        self.pushButton_accept.setText(_translate("Validation", "接受订单"))
        self.menuHelp.setTitle(_translate("Validation", "File"))
        self.actionMannual.setText(_translate("Validation", "Mannual"))
        self.actionAbout.setText(_translate("Validation", "About"))
        self.actionReadme.setText(_translate("Validation", "Readme"))
        self.actionImport.setText(_translate("Validation", "Import"))

